/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';

const components = [
  Button
];

const install = function(Vue, opts = {}) {
  components.map(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);

  Vue.prototype.$loading = Loading.service;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

module.exports = {
  version: '1.0.0',
  install,
  Loading,
  Button
};

module.exports.default = module.exports;
